### ISSUE TITLE
Gitkraken from AUR - `CURL_OPENSSL_3' not found 

### ISSUE THREAD

**Issue by paulogdm** [Azd325/gitkraken#61]
Hello everybody, if anyone can help me about this error (It started when I updated my system).
I was following the issue #38 and I dont know what went wrong since.
What I've tried so far:  
1. Installing/reinstalling dependencies, mostly the openssl one.
2. Changing or removing the LD_PRELOAD flag.

Any ideas?

Output from `/opt/gitkraken/gitkraken` (without LD flags):
```
Node started time: 1509974382163
/usr/lib/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by /opt/gitkraken/resources/app.asar.unpacked/node_modules/nodegit/build/Release/nodegit.node)
Error: /usr/lib/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by /opt/gitkraken/resources/app.asar.unpacked/node_modules/nodegit/build/Release/nodegit.node)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:187:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/gitkraken/resources/app.asar/node_modules/nodegit/dist/nodegit.js:11:12)
    at Object.<anonymous> (/opt/gitkraken/resources/app.asar/node_modules/nodegit/dist/nodegit.js:1031:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/gitkraken/resources/app.asar/src/appBootstrap/upgradeScripts/versionScripts/v1_5_0.js:7:17)
    at Object.<anonymous> (/opt/gitkraken/resources/app.asar/src/appBootstrap/upgradeScripts/versionScripts/v1_5_0.js:298:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/gitkraken/resources/app.asar/src/appBootstrap/upgradeScripts/versionScripts/index.js:5:28)
    at Object.<anonymous> (/opt/gitkraken/resources/app.asar/src/appBootstrap/upgradeScripts/versionScripts/index.js:17:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/gitkraken/resources/app.asar/src/appBootstrap/upgradeScripts/index.js:7:24)
    at Object.<anonymous> (/opt/gitkraken/resources/app.asar/src/appBootstrap/upgradeScripts/index.js:43:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at App.module.exports.app.on (/opt/gitkraken/resources/app.asar/src/appBootstrap/main.js:174:5)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:191:7)
```

**Comment by KillWolfVlad** [comment]
I don't have this issue on Arch Linux (with latest updates from official repo).

P.S. It is ancient bug. 😢 

## Legal way:

1) Upgrade your system
2) Rebuild and reinstall `libcurl-openssl-1.0` as depens for `gitkraken`
3) Reinstall `gitkraken` from `AUR`
4) Launch `gitkaken` from DW/WM menu or type `gitkraken` in terminal

## Legal and the easiest way (but MarcinWieczorek does not ❤️  it)

1) Look up to my ~~GitKraken-Pro-AUR~~ repo (99.9999% that everything should work without any troubles)

**Comment by paulogdm** [comment]
- [x] `Upgrade sys`. Done. Manjaro synced.
- [x] `Rebuild libcurl-openssl-1.0`. Ok, I did that. When trying to execute here -> Just a `segfault`.
- [x] `Reinstall gitkraken`. Ok, fresh gitkraken install. When trying to execute here -> `segfault` again.
PS: Trying to execute both `/usr/bin` script and `/usr/opt/gitkraken` directly. Without LD_PRELOAD -> `CURL_OPENSSL_3` error. With LD_PRELOAD -> `segfault`.

Let's try the usual stuff before I go into something like your repo. But I will take a look!

**Comment by KillWolfVlad** [comment]
I tried to reproduce this issue

1. Fresh install `Manjaro XFCE Edition (17.0.6)` in `VirtualBox`
2. Install `libcurl-openssl-1.0` as depens for `gitkraken`
3. Install `gitkraken` from `AUR`
4. Launch `gitkraken` via `/usr/bin/gitkraken` -> everything work, no `segfault`
6. If I launch `gitkraken` via `/usr/opt/gitkraken/gitkraken` -> `CURL_OPENSSL_3 not found` (it should be)

You also can try delete `gitkraken` files from home directory (or backup them) and launch `gitkraken`

- `~/.gitkraken`
- `~/.config/GitKraken`

~~or just use my repo~~

**Comment by paulogdm** [comment]
@KillWolfVlad Indeed I tried a fresh install too and no issues whatsoever... Its always with an update (obviously some package breaking, but why rebuilding deps is not fixing it I have no idea.). If you have time and curiosity, try a Manjaro old release and the problem will be reproduced...

No luck when moving config files...

The segfault output is `/usr/bin/gitkraken: line 3:  3239 Segmentation fault      (core dumped) LD_PRELOAD=/usr/lib/libcurl-openssl-1.0.so.4.4.0 /opt/gitkraken/gitkraken "$@"` . If I remember correctly 3239 is the offset for the function?

**Comment by KillWolfVlad** [comment]
> Manjaro old release

Manjaro is rolling. Only forward, not a step back! (very hard to reproduce)

> /usr/bin/gitkraken: line 3: 3239 Segmentation fault (core dumped)

Can you paste more informative log? Use this utilities

- `gdb`
- `strace`

**Comment by paulogdm** [comment]
@KillWolfVlad I know that! But you can install Manjaro 16.XX and then upgrade (with gitkraken installed) to reproduce this. Anyway, I have a computer with manjaro running (home) and another that its not (work). Maybe I could checksum both libcurl deps...
Tomorrow I will output the `gdb` info.

**Comment by paulogdm** [comment]
Yep, all synced between work and home computers... No luck at all. I'm 100% sure that this is some detail that Im missing, very weird that rebuilding all deps and gitkraken itself does'nt solve the issue.

**Comment by KillWolfVlad** [comment]
> very weird

I agree. I can't reproduce this issue (I tried install `GitKraken` on `Manjaro 16.06`, then upgrade, but all works without troubles)

> Can you paste more informative log? Use this utilities
> - gdb
> - strace

**Comment by paulogdm** [comment]
Sorry, forgot about gdb (my head is spinning around this shit, even when I sleep).
Here you go: (output from `strace gitkraken`)
```
execve("/usr/bin/gitkraken", ["gitkraken"], 0x7ffee5232bb0 /* 46 vars */) = 0
brk(NULL)                               = 0x5576d9b98000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=199937, ...}) = 0
mmap(NULL, 199937, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f0bcb024000
close(3)                                = 0
openat(AT_FDCWD, "/usr/lib/libreadline.so.7", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0n\1\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0555, st_size=363064, ...}) = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f0bcb022000
mmap(NULL, 2413768, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f0bcabe3000
mprotect(0x7f0bcac27000, 2097152, PROT_NONE) = 0
mmap(0x7f0bcae27000, 32768, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x44000) = 0x7f0bcae27000
mmap(0x7f0bcae2f000, 5320, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f0bcae2f000
close(3)                                = 0
openat(AT_FDCWD, "/usr/lib/libtinfo.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0000\331\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=178632, ...}) = 0
mmap(NULL, 2275712, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f0bca9b7000
mprotect(0x7f0bca9de000, 2097152, PROT_NONE) = 0
mmap(0x7f0bcabde000, 20480, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x27000) = 0x7f0bcabde000
close(3)                                = 0
openat(AT_FDCWD, "/usr/lib/libdl.so.2", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0@\r\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=14144, ...}) = 0
mmap(NULL, 2109584, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f0bca7b3000
mprotect(0x7f0bca7b6000, 2093056, PROT_NONE) = 0
mmap(0x7f0bca9b5000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) = 0x7f0bca9b5000
close(3)                                = 0
openat(AT_FDCWD, "/usr/lib/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\200\20\2\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=2065840, ...}) = 0
mmap(NULL, 3893456, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f0bca3fc000
mprotect(0x7f0bca5aa000, 2093056, PROT_NONE) = 0
mmap(0x7f0bca7a9000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1ad000) = 0x7f0bca7a9000
mmap(0x7f0bca7af000, 14544, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f0bca7af000
close(3)                                = 0
openat(AT_FDCWD, "/usr/lib/libncursesw.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0P\236\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=226936, ...}) = 0
mmap(NULL, 2322968, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f0bca1c4000
mprotect(0x7f0bca1fb000, 2093056, PROT_NONE) = 0
mmap(0x7f0bca3fa000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x36000) = 0x7f0bca3fa000
close(3)                                = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f0bcb020000
arch_prctl(ARCH_SET_FS, 0x7f0bcb020f80) = 0
mprotect(0x7f0bca7a9000, 16384, PROT_READ) = 0
mprotect(0x7f0bcabde000, 16384, PROT_READ) = 0
mprotect(0x7f0bca3fa000, 4096, PROT_READ) = 0
mprotect(0x7f0bca9b5000, 4096, PROT_READ) = 0
mprotect(0x7f0bcae27000, 8192, PROT_READ) = 0
mprotect(0x5576d8a1f000, 12288, PROT_READ) = 0
mprotect(0x7f0bcb055000, 4096, PROT_READ) = 0
munmap(0x7f0bcb024000, 199937)          = 0
openat(AT_FDCWD, "/dev/tty", O_RDWR|O_NONBLOCK) = 3
close(3)                                = 0
brk(NULL)                               = 0x5576d9b98000
brk(0x5576d9bb9000)                     = 0x5576d9bb9000
open("/usr/lib/locale/locale-archive", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=1686992, ...}) = 0
mmap(NULL, 1686992, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f0bcae84000
close(3)                                = 0
getuid()                                = 1000
getgid()                                = 1000
geteuid()                               = 1000
getegid()                               = 1000
rt_sigprocmask(SIG_BLOCK, NULL, [], 8)  = 0
ioctl(-1, TIOCGPGRP, 0x7ffe8f95a504)    = -1 EBADF (Bad file descriptor)
sysinfo({uptime=5545, loads=[121088, 98176, 91328], totalram=8248786944, freeram=3530444800, sharedram=696795136, bufferram=114941952, totalswap=9448923136, freeswap=9448923136, procs=877, totalhigh=0, freehigh=0, mem_unit=1}) = 0
rt_sigaction(SIGCHLD, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7f0bca430920}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGCHLD, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7f0bca430920}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7f0bca430920}, 8) = 0
rt_sigaction(SIGINT, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f0bca430920}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGINT, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f0bca430920}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f0bca430920}, 8) = 0
rt_sigaction(SIGQUIT, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f0bca430920}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGQUIT, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f0bca430920}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f0bca430920}, 8) = 0
rt_sigaction(SIGTSTP, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f0bca430920}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGTSTP, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f0bca430920}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f0bca430920}, 8) = 0
rt_sigaction(SIGTTIN, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f0bca430920}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGTTIN, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f0bca430920}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f0bca430920}, 8) = 0
rt_sigaction(SIGTTOU, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f0bca430920}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGTTOU, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f0bca430920}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f0bca430920}, 8) = 0
rt_sigprocmask(SIG_BLOCK, NULL, [], 8)  = 0
rt_sigaction(SIGQUIT, {sa_handler=SIG_IGN, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f0bca430920}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f0bca430920}, 8) = 0
uname({sysname="Linux", nodename="i3dell", ...}) = 0
stat("/home/pgdm/Codes/CrowdFunding/sails", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat(".", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/home", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/home/pgdm", {st_mode=S_IFDIR|0700, st_size=4096, ...}) = 0
stat("/home/pgdm/Codes", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/home/pgdm/Codes/CrowdFunding", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/home/pgdm/Codes/CrowdFunding/sails", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
getpid()                                = 8063
open("/usr/lib/gconv/gconv-modules.cache", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/lib/gconv/gconv-modules", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=56095, ...}) = 0
read(3, "# GNU libc iconv configuration.\n"..., 4096) = 4096
read(3, "1002//\tJUS_I.B1.002//\nmodule\tJUS"..., 4096) = 4096
read(3, "ISO-IR-110//\t\tISO-8859-4//\nalias"..., 4096) = 4096
read(3, "\t\tISO-8859-14//\nalias\tISO_8859-1"..., 4096) = 4096
read(3, "IC-ES//\nalias\tEBCDICES//\t\tEBCDIC"..., 4096) = 4096
read(3, "DIC-CP-ES//\t\tIBM284//\nalias\tCSIB"..., 4096) = 4096
read(3, "//\nalias\tCSIBM864//\t\tIBM864//\nal"..., 4096) = 4096
read(3, "BM939//\nmodule\tIBM939//\t\tINTERNA"..., 4096) = 4096
read(3, "EUC-CN//\nalias\tCN-GB//\t\t\tEUC-CN/"..., 4096) = 4096
read(3, "T//\nmodule\tISO-2022-CN-EXT//\tINT"..., 4096) = 4096
brk(0x5576d9bda000)                     = 0x5576d9bda000
read(3, "//\t\tISO_5428//\nalias\tISO_5428:19"..., 4096) = 4096
read(3, "CII-8\t1\n\n#\tfrom\t\t\tto\t\t\tmodule\t\tc"..., 4096) = 4096
read(3, "\tfrom\t\t\tto\t\t\tmodule\t\tcost\nalias\t"..., 4096) = 4096
read(3, "712//\t\tINTERNAL\t\tIBM12712\t\t1\nmod"..., 4096) = 2847
read(3, "", 4096)                       = 0
close(3)                                = 0
getppid()                               = 8061
getpid()                                = 8063
getpgrp()                               = 8061
ioctl(2, TIOCGPGRP, [8061])             = 0
rt_sigaction(SIGCHLD, {sa_handler=0x5576d879d850, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7f0bca430920}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7f0bca430920}, 8) = 0
prlimit64(0, RLIMIT_NPROC, NULL, {rlim_cur=31071, rlim_max=31071}) = 0
rt_sigprocmask(SIG_BLOCK, NULL, [], 8)  = 0
openat(AT_FDCWD, "/usr/bin/gitkraken", O_RDONLY) = 3
stat("/usr/bin/gitkraken", {st_mode=S_IFREG|0755, st_size=90, ...}) = 0
ioctl(3, TCGETS, 0x7ffe8f95a490)        = -1 ENOTTY (Inappropriate ioctl for device)
lseek(3, 0, SEEK_CUR)                   = 0
read(3, "#!/bin/sh\n\nLD_PRELOAD=/usr/lib/l"..., 80) = 80
lseek(3, 0, SEEK_SET)                   = 0
prlimit64(0, RLIMIT_NOFILE, NULL, {rlim_cur=1024, rlim_max=4*1024}) = 0
fcntl(255, F_GETFD)                     = -1 EBADF (Bad file descriptor)
dup2(3, 255)                            = 255
close(3)                                = 0
fcntl(255, F_SETFD, FD_CLOEXEC)         = 0
fcntl(255, F_GETFL)                     = 0x8000 (flags O_RDONLY|O_LARGEFILE)
fstat(255, {st_mode=S_IFREG|0755, st_size=90, ...}) = 0
lseek(255, 0, SEEK_CUR)                 = 0
read(255, "#!/bin/sh\n\nLD_PRELOAD=/usr/lib/l"..., 90) = 90
rt_sigprocmask(SIG_BLOCK, [INT CHLD], [], 8) = 0
clone(child_stack=NULL, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f0bcb021250) = 8064
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, [CHLD], [], 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, [CHLD], [], 8) = 0
rt_sigaction(SIGINT, {sa_handler=0x5576d879a0e0, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f0bca430920}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f0bca430920}, 8) = 0
wait4(-1, Node started time: 1510070753860
[{WIFSIGNALED(s) && WTERMSIG(s) == SIGSEGV && WCOREDUMP(s)}], 0, NULL) = 8064
rt_sigaction(SIGINT, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f0bca430920}, {sa_handler=0x5576d879a0e0, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f0bca430920}, 8) = 0
open("/usr/share/locale/locale.alias", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=2997, ...}) = 0
read(3, "# Locale name alias data base.\n#"..., 4096) = 2997
read(3, "", 4096)                       = 0
close(3)                                = 0
open("/usr/share/locale/en_US.UTF-8/LC_MESSAGES/bash.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en_US.utf8/LC_MESSAGES/bash.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en_US/LC_MESSAGES/bash.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en.UTF-8/LC_MESSAGES/bash.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en.utf8/LC_MESSAGES/bash.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en/LC_MESSAGES/bash.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
fstat(2, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 1), ...}) = 0
open("/usr/share/locale/en_US.UTF-8/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en_US.utf8/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en_US/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en.UTF-8/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en.utf8/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
write(2, "/usr/bin/gitkraken: line 3:  806"..., 151/usr/bin/gitkraken: line 3:  8064 Segmentation fault      (core dumped) LD_PRELOAD=/usr/lib/libcurl-openssl-1.0.so.4.4.0 /opt/gitkraken/gitkraken "$@"
) = 151
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_DUMPED, si_pid=8064, si_uid=1000, si_status=SIGSEGV, si_utime=96, si_stime=77} ---
wait4(-1, 0x7ffe8f959b90, WNOHANG, NULL) = -1 ECHILD (No child processes)
rt_sigreturn({mask=[]})                 = 0
read(255, "", 90)                       = 0
rt_sigprocmask(SIG_BLOCK, [CHLD], [], 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
exit_group(139)                         = ?
+++ exited with 139 +++
```

**Comment by KillWolfVlad** [comment]
>  forgot about `gdb`

May be `gdb` log will be more helpful. (`strace` looks normal ~~for noob~~)

**Comment by paulogdm** [comment]
There you go:
```
[pgdm@i3dell ~]$ gdb /opt/gitkraken/gitkraken 
GNU gdb (GDB) 8.0.1
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /opt/gitkraken/gitkraken...(no debugging symbols found)...done.
(gdb) set environment LD_PRELOAD=/usr/lib/libcurl-openssl-1.0.so.4.4.0
(gdb) start
Temporary breakpoint 1 at 0x3b88bb0
Starting program: /opt/gitkraken/gitkraken 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".

Temporary breakpoint 1, 0x0000000003b88bb0 in main ()
(gdb) 
(gdb) run
The program being debugged has been started already.
Start it from the beginning? (y or n) n
Program not restarted.
(gdb) info breakpoints 
No breakpoints or watchpoints.
(gdb) continue
Continuing.
[New Thread 0x7fffe5a45700 (LWP 13463)]
[New Thread 0x7fffe3d8d700 (LWP 13465)]
[New Thread 0x7fffe358c700 (LWP 13466)]
Node started time: 1510078229674
[New Thread 0x7fffe2d8b700 (LWP 13467)]
[New Thread 0x7fffe258a700 (LWP 13468)]
[New Thread 0x7fffe1d89700 (LWP 13469)]
[New Thread 0x7fffe08b5700 (LWP 13470)]
[New Thread 0x7fffe00b4700 (LWP 13471)]
[New Thread 0x7fffdf8b3700 (LWP 13472)]
[New Thread 0x7ffff7e1d700 (LWP 13473)]
[New Thread 0x7fffdf0b2700 (LWP 13474)]
[New Thread 0x7fffde8b1700 (LWP 13475)]
[New Thread 0x7fffde0b0700 (LWP 13476)]
[New Thread 0x7fffdd8af700 (LWP 13477)]
[New Thread 0x7fffdd0ae700 (LWP 13478)]
[New Thread 0x7fffdc8ad700 (LWP 13479)]
[New Thread 0x7fffdc0ac700 (LWP 13480)]
[New Thread 0x7fffdb8ab700 (LWP 13481)]
[New Thread 0x7fffdb0aa700 (LWP 13482)]
[New Thread 0x7fffda8a9700 (LWP 13483)]
[New Thread 0x7fffd91fa700 (LWP 13485)]
[New Thread 0x7fffc89f9700 (LWP 13486)]
[New Thread 0x7fffc782a700 (LWP 13490)]
[New Thread 0x7fffc7029700 (LWP 13491)]
[New Thread 0x7fffc6828700 (LWP 13492)]
[New Thread 0x7fffc6027700 (LWP 13493)]
[New Thread 0x7fffc5826700 (LWP 13494)]
[New Thread 0x7fffc5025700 (LWP 13495)]
[New Thread 0x7fffc4824700 (LWP 13496)]
[New Thread 0x7fffc4023700 (LWP 13497)]
[New Thread 0x7fffc3822700 (LWP 13498)]
[New Thread 0x7fffc3021700 (LWP 13499)]

Thread 1 "gitkraken" received signal SIGSEGV, Segmentation fault.
0x00007fffeed576d0 in SSL_CTX_set_verify () from /usr/lib/libssl.so.1.1
(gdb) quit
A debugging session is active.

	Inferior 1 [process 13406] will be killed.

Quit anyway? (y or n) y

```

**Comment by KillWolfVlad** [comment]
GREAT!!!!!

`pkgfile /usr/lib/libssl.so.1.1` -> `core/openssl`

Try reinstall `openssl`, `openssl-1.0`, `curl`, `libpsl`, `libssh2`, `krb5` and rebuild `libcurl-openssl-1.0`

**Comment by KillWolfVlad** [comment]
Remembered my `Manjaro 16.06` experience

I think you broke your `core` system from this update https://bbs.archlinux.org/viewtopic.php?id=225528

**Comment by paulogdm** [comment]
Doing `pacman -S <package>` and also with `-Syu` (Im at that level of desperation where you know that wont work but you do it anyway just in case ☹ ).
I will try working on `core` tomorrow. Any tips?

**Comment by MarcinWieczorek** [comment]
@KillWolfVlad I really appreciate your support which is huge, but please take your gitkraken pro stuff off public conversations.

**Comment by paulogdm** [comment]
1. `pacman -S $(pacman -Qqen)` >> No luck at all.
(Uninstalled Gitkraken with `-Rs` option).
2. `pacman -Rsn $(pacman -Qdtq)` and then reinstalled gitkraken.  >> Big nope.
3. Tried to forceful remove `libcurl-openssl-1.0` and then reintall `openssl, openssl-1.0, curl, libpsl, libssh2, krb5` >> nopenope.
PS: When executing, I tried both the bin script (with LD_PRELOAD flag) and `/opt/gitkraken/gitkraken` directly, because it worked on my home computer >> https://forum.manjaro.org/t/trying-to-install-gitkraken-no-luck-at-all/31314/5

**Comment by paulogdm** [comment]
@KillWolfVlad Im trying your repo right now. But I will not use PRO for several reasons... Anyway lets see if gitkraken will work now.

**Comment by paulogdm** [comment]
More info: Im unable to reproduce this on my personal computer. After doing a full system upgrade, just reinstalling libcurl-openssl-1.0 fixed gitkraken. Idk why gitkraken refuses to launch at my work pc. Im making a zip with my libs so I can explore wich one is faulting.

**Comment by paulogdm** [comment]
Victory!!!
Im ashamed of my solution, by deep I dont really care because it is working.
here it is:
1. Grab every lib file like `tar -czvf libs.tgz /lib/libcurl*` (home computer - Gitkraken working).
2. Compare every lib file against my local files (work computer).
3. Diff found, one file existed in `/lib/libcurl-openssl-1.0/<name of file>` that is not on my original folder.
3.1 I cant remember the name of this file, but I have just 3 on both computers now: `/lib/libcurl-openssl-1.0/libcurl.so  /lib/libcurl-openssl-1.0/libcurl.so.4  /lib/libcurl-openssl-1.0/libcurl.so.4.4.0
`.
4- Fixed. Im pretty sure a bad symlink was causing this issue, reinstalling packages did not solve because the link was always there.
