### ISSUE TITLE
Depend on brotli

### ISSUE THREAD

**Issue by charlieman** [Azd325/gitkraken#68]
Hi,

I purged dependency packages that were no longer needed from my system (using `pacman -Qdtq | pacman -Rs -`) and gitkraken stopped working because it couldn't find `libbrotlidec.so.1`. Reinstalling `brotli` fixed it, so it seems to be a direct dependency of gitkraken.

**Comment by KillWolfVlad** [comment]
I does not have package `brotli` and `gitkraken` works well

```
$ yaourt -Qi brotli
error: package 'brotli' was not found
```

**Comment by MarcinWieczorek** [comment]
`ldd` doesn't show that gitkraken executable is linked to libbrotli. Please provide some logs, traces or something. You might have had done a partial upgrade and something else caused it.

**Comment by charlieman** [comment]
Ok, I just removed brotli and tried to run gitkraken on the console and got this:

```
$ LANG=C gitkraken
Node started time: 1517344823748
libbrotlidec.so.1: cannot open shared object file: No such file or directory
Error: libbrotlidec.so.1: cannot open shared object file: No such file or directory
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:187:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/gitkraken/resources/app.asar/node_modules/nodegit/dist/nodegit.js:11:12)
    at Object.<anonymous> (/opt/gitkraken/resources/app.asar/node_modules/nodegit/dist/nodegit.js:1031:3)
```
After reinstalling it worked fine. I'm not well versed in node but it seems to be a dynamic dependency.

**Comment by Azd325** [comment]
Please reopen if you can provide more information about this problem/system.
